# Generated by Django 3.1.2 on 2020-10-21 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('post', models.TextField()),
                ('post_type', models.CharField(choices=[('FAMILY', 'FAMILY'), ('WORK', 'WORK'), ('PERSONAL', 'PERSONAL')], default='PERSONAL', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_date')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='modified_date')),
                ('completion_status', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
